name: mirror to Docker Hub

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build and push to GHCR"]
    types: [completed]

permissions:
  contents: read
  packages: write

jobs:
  mirror-from-ghcr:
    name: Mirror image from GHCR to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Derive repository name
        id: repo
        run: echo "name=${GITHUB_REPOSITORY#*/}" >> "$GITHUB_OUTPUT"
      - name: Detect newest and max upstream semver tags
        id: upstream
        run: |
          set -euo pipefail
          DATA=$(curl -fsSL "https://hub.docker.com/v2/repositories/grafana/mimir/tags?page_size=100")
          # Most recently updated semver (could be a backport like 2.16.x after 2.17.0)
          NEWEST=$(echo "$DATA" \
            | jq -r '[.results[] | select(.name | test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))] | sort_by(.last_updated) | last | .name')
          # Maximum semver (the highest X.Y.Z)
          MAX=$(echo "$DATA" \
            | jq -r '.results[].name' \
            | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' \
            | sort -V \
            | tail -n1)
          if [ -z "${NEWEST}" ] || [ -z "${MAX}" ]; then
            echo "No semver tags found on Docker Hub in 100 recent tags" >&2
            exit 1
          fi
          echo "Newest upstream tag: ${NEWEST} (max semver: ${MAX})"
          echo "version=${NEWEST}" >> "$GITHUB_OUTPUT"
          echo "max_version=${MAX}" >> "$GITHUB_OUTPUT"
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check if Docker Hub tag already exists
        id: check
        run: |
          set -euo pipefail
          IMAGE="docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ steps.repo.outputs.name }}:${{ steps.upstream.outputs.version }}"
          if docker manifest inspect "$IMAGE" >/dev/null 2>&1; then
            echo "Image already exists: $IMAGE"
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "Image does not exist: $IMAGE"
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Mirror manifest from GHCR to Docker Hub
        if: steps.check.outputs.exists == 'false'
        run : |
          set -euo pipefail
          SRC="ghcr.io/${{ github.repository }}:${{ steps.upstream.outputs.version }}"
          DST_BASE="docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ steps.repo.outputs.name }}"
          TAG_ARGS=("--tag" "${DST_BASE}:${{ steps.upstream.outputs.version }}")
          if [ "${{ steps.upstream.outputs.version }}" = "${{ steps.upstream.outputs.max_version }}" ]; then
            TAG_ARGS=("--tag" "${DST_BASE}:latest" "${TAG_ARGS[@]}")
          fi
          docker buildx imagetools create "${TAG_ARGS[@]}" "${SRC}"
      - name: Up-to-date (no new version to mirror)
        if: steps.check.outputs.exists == 'true'
        run: echo "Docker Hub already has tag ${{ steps.upstream.outputs.version }}"
